# PHP-FPM
FROM php:8.3-fpm-alpine

# Rendszer csomagok és PHP extensionök telepítése (ZIP, CURL, GIT, PostgreSQL)
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    libpq-dev \
    curl \
    git


RUN docker-php-ext-install zip pdo pdo_pgsql

# Munkakönyvtár beállítása
WORKDIR /var/www

# Composer telepítés
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer